"""empty message

Revision ID: 003447a52ed6
Revises: 7457ec15fb9a
Create Date: 2024-04-06 20:44:31.965054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003447a52ed6'
down_revision = '7457ec15fb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
