"""empty message

Revision ID: 3dda16223778
Revises: 003447a52ed6
Create Date: 2024-04-06 20:47:25.130440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dda16223778'
down_revision = '003447a52ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.drop_column('endDate')
        batch_op.drop_column('startDate')
        batch_op.drop_column('startTime')
        batch_op.drop_column('endTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endTime', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('startTime', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('startDate', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('endDate', sa.DATE(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_time')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
