"""empty message

Revision ID: 7457ec15fb9a
Revises: a839b15dc87d
Create Date: 2024-04-06 20:33:31.607028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7457ec15fb9a'
down_revision = 'a839b15dc87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymentRequired', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('paymentAmount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('startTime', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('endTime', sa.Time(), nullable=True))
        batch_op.alter_column('startDate',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('endDate',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_column('isPaidOnly')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isPaidOnly', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('endDate',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('startDate',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('endTime')
        batch_op.drop_column('startTime')
        batch_op.drop_column('paymentAmount')
        batch_op.drop_column('paymentRequired')

    # ### end Alembic commands ###
