"""empty message

Revision ID: acf277bbc730
Revises: 33cd86c91735
Create Date: 2024-04-15 19:02:04.579057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf277bbc730'
down_revision = '33cd86c91735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('rsvp_names', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.drop_column('startDate')
        batch_op.drop_column('endTime')
        batch_op.drop_column('endDate')
        batch_op.drop_column('startTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startTime', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('endDate', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('endTime', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('startDate', sa.DATE(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_time')
        batch_op.drop_column('start_date')

    op.drop_table('event_list')
    # ### end Alembic commands ###
